### ISSUE TITLE
xattr test fails

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/tar-rs#100]
```
failures:

---- xattrs stdout ----
	thread 'xattrs' panicked at 'ar.unpack(td.path()) returned failed to unpack `/tmp/tar-rs.hZDRDsDKcBM8/a/b`', tests/all.rs:187
stack backtrace:
   1:     0x56059bfa625a - std::sys::imp::backtrace::tracing::imp::write::hd9cb4c1797101742
   2:     0x56059bfaaedf - std::panicking::default_hook::{{closure}}::h154dea97b11a961f
   3:     0x56059bfaaa7d - std::panicking::default_hook::h7b2373844128ce08
   4:     0x56059bfab387 - std::panicking::rust_panic_with_hook::h8d52d23c1df454da
   5:     0x56059bfab1c4 - std::panicking::begin_panic::h031e0a076e248818
   6:     0x56059bfab139 - std::panicking::begin_panic_fmt::hcd972326ec953c01
   7:     0x56059bf433b4 - all::xattrs::h24b27a574085ec14
                        at /builddir/build/BUILD/tar-0.4.10/tests/all.rs:187
   8:     0x56059bf67e0e - <F as test::FnBox<T>>::call_box::ha9ae2c58fadcb2d4
   9:     0x56059bfb3bfa - __rust_maybe_catch_panic
  10:     0x56059bf5c25a - std::panicking::try::do_call::h8e5d0728aa750f11
  11:     0x56059bfb3bfa - __rust_maybe_catch_panic
  12:     0x56059bf62ed2 - <F as alloc::boxed::FnBox<A>>::call_box::h882735c009d3deef
  13:     0x56059bfaa1e4 - std::sys::imp::thread::Thread::new::thread_start::hc88703e10b184eab
  14:     0x7fd3f39055bc - start_thread
  15:     0x7fd3f3427c3e - __GI___clone
  16:                0x0 - <unknown>


failures:
    xattrs

test result: FAILED. 34 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by ignatenkobrain** [comment]
no_xattr passes, so meh

**Comment by alexcrichton** [comment]
I unfortunately can't reproduce this locally, can you describe how to reproduce this?

**Comment by ignatenkobrain** [comment]
I don't know, I ran `cargo test` on my laptop. Probably this is due to our rustc compiled without jemalloc (See https://github.com/servo/heapsize/issues/74),

**Comment by aidanhs** [comment]
Might be worth trying the xattr tests - https://github.com/Stebalien/xattr

**Comment by ignatenkobrain** [comment]
@aidanhs only one test was failing -- https://github.com/Stebalien/xattr/issues/9

**Comment by aidanhs** [comment]
Cool, just need to update xattr in tar-rs to 0.1.11 then.

**Comment by ignatenkobrain** [comment]
@aidanhs when I was reporting this issue, I already had 0.1.11. And it was just some problem in tests in xattr, so it's completely unrelated to this issue.

**Comment by ids1024** [comment]
This seems to be because `/tmp` is a tmpfs, which doesn't seem to support xattr. Changing the test to use `TempDir::new_in` with a normal partition fixes it.

I don't know what a correct fix would be; I'm not sure there is one.

**Comment by ids1024** [comment]
It looks like the tests in the xattr crate use `/var/tmp` for this reason; there is probably no truly sound and portable way to do this though (but luckily it's only a unit test).
