### ISSUE TITLE
Builder::append_dir_all not found on Stable-MSVC

### ISSUE THREAD

**Issue by valarauca** [alexcrichton/tar-rs#101]
The docs say there is an `append_dir_all` for `tar::Builder<W>`. But I've attempted to build this with stable-msvc (1.15.1, 64bit) and I get the error `no method append_dir_all for tar::Builder<std::fs::File>`

That is on `v0.4` and `v0.4.10`

To re-create

```rust
extern crate tar
use tar:: Builder;
use std::path::Path;
use std::io::{self,Write};
pub fn append_dir<A,B,W>(b: &mut Builder<W>, a: A, b: B) -> io::Result<()>
where
    A: AsRef<Path>,
    B: AsRef<Path>,
    C: Write
{
    b.append_dir_all(a,b)
}
```

[Doc Ref](http://alexcrichton.com/tar-rs/tar/struct.Builder.html#method.append_dir_all)

[Source Ref](https://github.com/alexcrichton/tar-rs/blob/master/src/builder.rs#L211-L216)

I'm really confused

**Comment by aidanhs** [comment]
There hasn't been a release since that PR got merged, but @alexcrichton pushes the docs daily, so you're seeing what's on the top of master.

See https://docs.rs/tar/0.4.10/tar/struct.Builder.html for the docs for 0.4.10.

**Comment by valarauca** [comment]
Ah okay thanks for clearing that up. 

I cloned locally and tested it out. It doesn't appear to exit. 

This never exits on stable-msvc
```rust
builder.append(path, ".")?; 
```

**Comment by alexcrichton** [comment]
Ah yeah I just haven't published a version yet, this'll get picked up in the next vesion though!
