### ISSUE TITLE
Support "." as first argument of append_dir_all()

### ISSUE THREAD

**Issue by ids1024** [alexcrichton/tar-rs#103]
The command `builder.append_dir_all(".", "foo")` fails with the error "paths in archives must have at least one component".

It seems like it would be useful to support this, to populate the root of the archive from the contents of a folder. So `foo/bar` would be in the archive as `./bar`, etc. Does this seem like a good thing to add, or is there a better way to do this?

Implementing this should just be a matter of not calling `append_dir()` for the top level directory if it is `.`.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by ids1024** [comment]
Now that I look at #68, it seems `.` actually is a valid name for a directory in a tar archive (testing with GNU tar confirms that). Although that seems a bit odd.

Since the behavior I am looking for is not to create a directory in the archive, maybe using a blank string (`.append_dir_all("", "foo")`)  would be better.
