### ISSUE TITLE
Long filenames when adding via append<R: Read>

### ISSUE THREAD

**Issue by the8472** [alexcrichton/tar-rs#108]
It would be great if the logic that automatically [prepends a long filename header](https://github.com/alexcrichton/tar-rs/blob/1647ce76ee09cfed3fb0e909517ac7e65e3a1f6c/src/builder.rs#L282-L303) was also available for the `append` method. Currently the code is not reusable and has to be copy-pasted if one wants to pass in `Read` implementations associated with long file names as opposed to `Path`.

**Comment by alexcrichton** [comment]
Seems fine to me! I'd be ok adding a new `append_*`-style method to use this logic.
