### ISSUE TITLE
Need a way to add executable Windows files

### ISSUE THREAD

**Issue by cuviper** [alexcrichton/tar-rs#109]
I'm looking how to whitelist Windows files that should be marked executable, as discussed in rust-lang/rust#42121, but I don't see a clean way to do this.  The easy `Builder::append_path()` and `append_file()` methods call `append_fs()` which fills the header mode from file metadata, and the Windows `fill_platform_from()` only considers whether files are read-only.  (There's not a Windows concept of "executable" mode unless you dip into ACLs.)

AFAICS the only method we have for setting a manual mode is `Builder::append()` with your own header, but that will miss an important bit in `append_fs()` which deals with paths that are too long for a normal GNU header.  I don't think we want that logic duplicated by `tar` users.

So I think `Builder` will need a new method to give more control over the file mode, while keeping other niceties like long-path handling.

**Comment by cuviper** [comment]
I suppose another alternative is to just create the executable whitelist directly in Windows `fill_platform_from`.  Or even just have that mark *all* files executable, since the default ACLs for new files on Windows include X anyway.

**Comment by alexcrichton** [comment]
Ah yeah the intention here is that this crate exports enough "helper APIs" to do roughly what `append_fs` does without much ado, so maybe https://github.com/alexcrichton/tar-rs/issues/108 is just needed here?
