### ISSUE TITLE
File size problem when using append_dir_all?

### ISSUE THREAD

**Issue by sb89** [alexcrichton/tar-rs#111]
I have a directory with three files inside (2.1 kB, 73.9 kB, 8.9 kB).

This is my code:

```
use std::io::prelude::*;
use flate2::Compression;
use flate2::write::GzEncoder;
use std::fs::File;
use tar::Builder;


fn main() {
    let mut ar = Builder::new(Vec::new());
    ar.append_dir_all("test", "/home/steven/compression_folder").unwrap();

    let data = ar.into_inner().unwrap();

    let output_archive = File::create("foo.tar.gz").unwrap();

    let mut enc = GzEncoder::new(output_archive, Compression::Default);
    enc.write(data.as_slice()).unwrap();
}
```

When I try to extract (using `tar -xvf foo.tar.gz`), I get the following error:

> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now

<del>If I change `append_dir_all` to `append_dir`, there are no errors when extracting.</del>

If I change back to `append_dir_all` and remove the largest file (73.9 kB), there are no errors when extracting.

**Comment by alexcrichton** [comment]
Hm sounds suspicious! Would it be possible to share the files in question?

**Comment by sb89** [comment]
I tried it with a random image (from google images) file in my directory, get the error with `append_dir_all` but not with `append_dir`.

Here is the image https://raw.githubusercontent.com/repejota/docker-vim-rust/master/screenshot.png

**Comment by sb89** [comment]
Ignore my comments on `append_dir`, I've just realised what this does and it's not relevant to this problem.

I've replicated this issue by trying to tar and compress the following file in my directory using `append_dir_all`:

https://raw.githubusercontent.com/repejota/docker-vim-rust/master/screenshot.png

**Comment by alexcrichton** [comment]
Ok managed to reproduce and thanks for the report! The bug here actually is that you're using `enc.write` instead of `enc.write_all`, so it's doing a short write and ending up only compressing some of the tarball, not the entire tarball. If you change it to `enc.write_all(...)` that should do the trick!
