### ISSUE TITLE
Documentation for `Builder` ignores result from `Header::set_path`

### ISSUE THREAD

**Issue by gyscos** [alexcrichton/tar-rs#114]
The examples for `Builder` include a few calls to `Header::set_path` but ignore its `Result`. Reading these examples, it's not clear a `Result` is returned at all.

Maybe this is intentional, since the focus is on `Builder` rather than `Headers`? Still, adding `.unwrap()` might make things clearer.

**Comment by alexcrichton** [comment]
Adding unwrap seems fine by me!
