### ISSUE TITLE
Absolute symlink acquires extra slash

### ISSUE THREAD

**Issue by taralx** [alexcrichton/tar-rs#125]
Creating a symlink to an absolute path results in an extra leading slash being added.

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have a test case which showcases this behavior?

**Comment by taralx** [comment]
I added the following to the absolute_symlink test:

```rust
let mut entries = t!(ar.entries());
let entry = t!(entries.next().unwrap());
let name = t!(String::from_utf8(entry.link_name_bytes().unwrap().into_owned()));
assert_eq!(name, "/bar");
```
