### ISSUE TITLE
Decompression API forces you to write to files

### ISSUE THREAD

**Issue by est31** [alexcrichton/tar-rs#133]
From what I've seen, there is no way to avoid writing files to the file system. This is bad if you just want to extract some info from files without actually doing anything with the files later on. It would be really cool if there would be two additional functions on the `Entry` struct:

* one function that returns `Result<Vec<u8>>` with the file contents.
* a second function that captures `self` and returns a `DecompressedEntry` struct that impl's `Read + Seek`, which can be converted into `self` again once done.

I especially would really be happy if the first function were available, the second would be nice (especially if you have compressed files inside compressed files), but is of a lower priority for me.

**Comment by alexcrichton** [comment]
Can you describe how writing to a file is forced? I've used this library many many times without ever touching the filesystem.

**Comment by est31** [comment]
@alexcrichton I'm creating a `tar::Archive` from something that impl's `Read`. Then I iter over the `entries()` of that Archive. I obtain `tar::Entry` objects. Now which function do I call to get the decompressed buffer of the `Entry`? [This is its rustdoc](https://docs.rs/tar/0.4.13/tar/struct.Entry.html). I only see functions that touch the filesystem. The `raw_file_position` function doesn't seem useful as it doesn't seem to work for "sparse" files, whatever those are.

**Comment by alexcrichton** [comment]
`impl Read for Entry`?

**Comment by est31** [comment]
Oh right... Would be cool to have `Seek` as well, but my use case is covered by `Read` already. Thanks for the help!
