### ISSUE TITLE
Directory permissions

### ISSUE THREAD

**Issue by zolnov** [alexcrichton/tar-rs#134]
Seems like, that upon untar() the library is creating directories with the default rwxr-xr-x mode even if the tar itself contains different permissions.

Starting from here:
https://github.com/alexcrichton/tar-rs/blob/d7977e748aacadb8431293087eee4bdc99e225ed/src/entry.rs#L384

1. The code finds a directory entry
2. If the dir exists does nothing
3. Otherwise it creates it with the default permissions

A 4. step could be to set_mode the directory with the permissions of the tar entry. Or do I miss something?

**Comment by alexcrichton** [comment]
Makes sense to me! Seems like a reasonable change to have!

**Comment by zolnov** [comment]
Thinking about it a bit:
1. All directories that need permission change have to be remembered
2. Permissions should be changed as last step of extraction

Otherwise there will be problems with the non writable (r-x) directories...

**Comment by alexcrichton** [comment]
AFAIK no progress, but a PR would be most welcome!

**Comment by joshleeb** [comment]
Started writing up a PR for this but looks like it might have been implemented already? 

https://github.com/alexcrichton/tar-rs/blob/c7b31b28d42631a39af6b3f3f05891abc104fdd3/src/entry.rs#L582
