### ISSUE TITLE
Single entry archives without parent directory?

### ISSUE THREAD

**Issue by Qard** [alexcrichton/tar-rs#14]
I see there is an an `unpack(...)` method on `Archive`. Any chance of getting a convenient way to extract the contents of single top-level entry archives without the parent directory?

**Comment by alexcrichton** [comment]
Hm I'm not quite sure what you mean by "single top-level entry archives without the parent directory", could you elaborate a little more?

**Comment by Qard** [comment]
Depending on the archiving tool, when you archive a folder you might get an archive containing the contents of the folder directly at the archive root, or you might get the single folder at the archive root with the contents inside that folder. It'd be nice if I could skip one level in and get the folder contents when there is only the one folder at the archive root.

What would actually be nice is to be able to unpack from any level in the tree.

**Comment by alexcrichton** [comment]
Ah I see, this does sound interesting! It sounds like a job that may be best done with iterators, but I'd have to think about it.

**Comment by alexcrichton** [comment]
Ok I've pushed an update adding `File::unpack` as a method. This should help situations like this as you can just iterate over the files in an archive, using the `unpack` method after doing custom munging of the path name for situations like this.
