### ISSUE TITLE
Don't allocate the vector for every entry

### ISSUE THREAD

**Issue by SoniEx2** [alexcrichton/tar-rs#141]
Since I'll be skipping through lots of entries I'd rather not allocate and immediately deallocate a vector for every entry.

**Comment by NightRa** [comment]
The library doesn't allocate or stored any file's data when `Archive::entries` is used.
Thus your use case is indeed already supported.

**Comment by SoniEx2** [comment]
okay, this is a 10 months old issue. when I checked back then, it did.

**Comment by alexcrichton** [comment]
Alright, let's close then!
