### ISSUE TITLE
append_dir_all appears to be working, but is returning an error

### ISSUE THREAD

**Issue by nellshamrell** [alexcrichton/tar-rs#147]
Hello!

I'm using append_dir_all to recursively add a directory and all subdirectories to a tar archive list this:

```
    let tarball_name = "my_tarball.gz";

    let tarball = File::create(tarball_name).unwrap();
    let mut tar_builder = Builder::new(tarball);

    let hab_pkgs_path = temp_dir_path.clone().join("rootfs/hab");

    tar_builder.append_dir_all("hab", hab_pkgs_path);
```

The odd thing is this code DOES work - it recursively adds the directory to the tar archive - but this line

```
tar_builder.append_dir_all("hab", hab_pkgs_path);
```

returns this error "thread 'main' panicked at 'could not export.: "Is a directory (os error 21)"', /checkout/src/libcore/result.rs:906:4"

I have been trying different things, googling left and right, running backtraces, and I have been unable to find a solution to this error.  Do you know of anything in this code that might cause that?

**Comment by alexcrichton** [comment]
Oh dear if that panics then it's definitely a bug! Can you run with `RUST_BACKTRACE` and gist that?

**Comment by nellshamrell** [comment]
Absolutely!  Here is the output from running with RUST_BACKTRACE

(Note - I am running the code above from a crate called hab_pkg_export_tar and a function called by another function called "export")

https://gist.github.com/nellshamrell/e4d9945c2a38f80cf13c345f39c93d23

**Comment by alexcrichton** [comment]
Oh ok, so the panic it seems is coming from the application code? Do you perhaps have a test case I could reproduce this error with?

**Comment by boastful-squirrel** [comment]
I think #48 solves this issue

**Comment by alexcrichton** [comment]
Thanks!
