### ISSUE TITLE
Can't extract gcc 7.2.0

### ISSUE THREAD

**Issue by Arcterus** [alexcrichton/tar-rs#154]
Given the file `gcc-7.2.0.tar.xz` from [here](https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz), tar-rs consistently fails to extract the decompressed `gcc-7.2.0.tar` archive using the following code:
```rust
extern crate tar;

fn main() {
    let file = std::fs::File::open("gcc-7.2.0.tar").unwrap();

    let mut archive = tar::Archive::new(file);
    archive.unpack(std::path::Path::new("testpath")).unwrap();
}
```

It always spits out this error:
```
Custom { kind: Other, error: TarError { desc: "failed to unpack `testpath/gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation`", io: Custom { kind: Other, error: TarError { desc: "failed to unpack `gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation/` into `testpath/gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation`", io: Os { code: 21, kind: Other, message: "Is a directory" } } } } }
```

**Comment by Arcterus** [comment]
It seems that it fails on what `file` claims is a "POSIX tar archive" (I assume this means pax).  When I extract `gcc-7.2.0.tar` with GNU `tar` and create a GNU tar archive, tar-rs is perfectly happy.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this should be fixed by https://github.com/alexcrichton/tar-rs/pull/155, mind testing that out and seeing if it works?

**Comment by Arcterus** [comment]
Yes, that fixes the issue.  Thanks!
