### ISSUE TITLE
Untar expects file, but produces directory

### ISSUE THREAD

**Issue by wisechengyi** [alexcrichton/tar-rs#173]
See repro at https://github.com/wisechengyi/rust_tar_repro

Encountered during https://github.com/pantsbuild/pants/pull/6748 where we try to migrate python's tar lib to rust tar lib for performance reasons.

**Comment by alexcrichton** [comment]
Thanks so much for the detailed bug report! Turns out this was a bug introduced quite recently, and I'll publish a new version to make sure it's fixed on crates.io
