### ISSUE TITLE
Potential usage with wasm?

### ISSUE THREAD

**Issue by mpizenberg** [alexcrichton/tar-rs#189]
Hi, I'm currently trying to evaluate if I could port an application of mine to wasm. One of the requirements is being able to read a lot of files from a folder. So I'm wondering if dropping an archive in the web app could do it.

I'm not familiar with tar-rs, mostly exploring options so sorry if the question doesn't fit the scope of the lib. Basically, do you think tar-rs could be used with wasm-bindgen (web_sys in particular which has a notion of File, Blob, etc.)?

**Comment by alexcrichton** [comment]
It sort of depends on what you want to do, but it is in theory compatible. You won't be able to use functions like `unpack` and such, but iteration, creation, and reading archives all works with arbitrary `Read`/`Write` types which can be implemented for wasm for types like `Blob` and such.

**Comment by mpizenberg** [comment]
In my current "normal" program, I have a folder with the following structure:

```
folder/
  - list-imgs.txt  (each line contains something like: `0 img/0.png`)
  - img/
    - 0.png
    - ...
```

Basically my program takes the file `list-imgs.txt` as an argument and then process all the images listed in it, starting by loading them with the `image` crate.

From what I understand, the first step would be to try to load them from the archive directly. I might have to copy the archive entries into a map of bytes. Then I have to verify that I can use the image crate to read from bytes instead of from a file. Checking wasm compatibility will only happen after all this is sorted out.

Thanks for the answer! I'll try it out when I find some time, and I'll let you know if I eventually manage to have a minimalist wasm example usage.
