### ISSUE TITLE
Out of order, low memory footprint, archive reading?

### ISSUE THREAD

**Issue by mpizenberg** [alexcrichton/tar-rs#190]
Hi again, from my quest of running an image processing program in wasm (#189) I've been trying to make it work from a tar archive. It does work so thanks for that! What I'm struggling with now, is reducing the memory footprint of the program.

Since I need out-of-order access to the images inside the tar, I'm currently building a hashmap containing buffers for every file. Unfortunately, doing so takes roughly 1GB of memory for a 500MB tar file. In the context of wasm, this would be even worse since the tar itself is loaded in the browser, so it will sum to roughly 1.5GB of memory.

In an attempt to reduce this to the strict minimum (500MB in a wasm context) and almost nothing in a desktop context, I've tried storing the `Entry` in the hashmap, and reading them later when needed in the program. As mentionned in the doc for `Archive::entries()` they should be processed in sequence. So with no surprise, it did not work XD.

I'm trying to circumvent this issue without success, any idea of how I should process?

**Comment by alexcrichton** [comment]
Thanks for the report! This library is intended to be pretty thin and not actually allocate anything internally, so are you sure that you're not accidentally storing copies of files and such elsewhere? 

It in theory is possible with this library to get entries, learn about their content offset, and then just use indices to refer to files and not actually duplicate the contents themselves.

**Comment by mpizenberg** [comment]
Yes, for the "out of order" case, to simply make it work, I initially stored the actual buffers (so yes, sort of a "copy" in memory) in a hashmap (file names as keys). As you suggested, and someone else in this [reddit post](https://www.reddit.com/r/rust/comments/be7gg5/memory_efficient_way_of_storing_tar_archive_data/), I made a separate data structure where I stored the offsets and sizes only. Now I managed to make it work correctly.

So the key point here is **build data structure with bytes offset and sizes of the entries**. I guess this solved my issue, (that was not so difficult in the end), so I'll close this. But at least, it makes a reference use case if you intend to add out-of-order tar entries reading later.

In practice, I used the following code:

```rust
struct FileEntry {
    offset: u64,
    length: u64,
}

fn get_buffer<R: Read + Seek>(
    name: &str,
    file: &mut R,
    entries: &HashMap<String, FileEntry>,
) -> Result<Vec<u8>, std::io::Error> {
    let entry = entries.get(name).expect("Entry is not in archive");
    read_file_entry(entry, file)
}

fn read_file_entry<R: Read + Seek>(
    entry: &FileEntry,
    file: &mut R,
) -> Result<Vec<u8>, std::io::Error> {
    let mut buffer = vec![0; entry.length as usize];
    file.seek(SeekFrom::Start(entry.offset))?;
    file.read_exact(&mut buffer)?;
    Ok(buffer)
}
```
