### ISSUE TITLE
Compilation to WebAssembly (wasm-bindgen) failing due to filetime dependency

### ISSUE THREAD

**Issue by mpizenberg** [alexcrichton/tar-rs#191]
Hi again ^^, I just added tar as a dependency to a minimalist wasm skeleton code and compilation failed. It appears that the failing happens when compiling the filetime crate.

```
$> wasm-pack build --target web

...

error[E0433]: failed to resolve: could not find `unix` in `os`
 --> /home/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.2.4/src/unix/mod.rs:6:14
  |
6 | use std::os::unix::prelude::*;
  |              ^^^^ could not find `unix` in `os`
```

Is this something that can be bypassed? Should I report the issue directly to the filetime crate?

I set up a minimalist github repo that you can just clone and build to test things: https://github.com/mpizenberg/wasm-tar

**Comment by alexcrichton** [comment]
Ah that actually looks like the `filetime` crate is the one not compiling, should be easy enough though I think to send a PR there to ensure it compiles but just returns errors!

**Comment by mpizenberg** [comment]
I've found those two pages [1,2] of the rustwasm book, that helped me understand better what hinders wasm compatibility. I don't understand however what you mean by "ensure it compiles but just returns errors".

From what I gather though, system librairies and file interactions are things not working with wasm. And so when I compile filetime with `cargo build --target wasm32-unknown-unknown`, I get a lot of "unresolved imports", "cannot find value '...' in module libc", etc. Adding wasm support to the filetime crate doesn't seem obvious to me.

In any case, I think (let me know if I'm wrong) that filetime is only used for `unpack` in the tar-rs crate. And unpacking should not be useful for wasm target. Is there a way of not providing the unpacking functionalities for the wasm32-unknown-unkown target?

[1] https://rustwasm.github.io/docs/book/reference/which-crates-work-with-wasm.html
[2] https://rustwasm.github.io/docs/book/reference/add-wasm-support-to-crate.html

**Comment by mpizenberg** [comment]
I think I got what you meant! I was looking for other crates with the same issues and found a wasm PR for clap: https://github.com/clap-rs/clap/pull/1190/commits/689949e57d390bb61bc69f3ed91f60a2105738d0

It contained things like:

```
#[cfg(all(feature = "debug", not(target_arch = "wasm32")))]
use std::os::unix::ffi::OsStrExt;

#[cfg(not(any(target_os = "windows", target_arch = "wasm32")))]
use std::os::unix::ffi::OsStrExt;

#[cfg(any(target_os = "windows", target_arch = "wasm32"))]
use osstringext::OsStrExt3;
```

So I guess I can try to add thos type of configurations in the code of tar. I'll try something and let you know.

**Comment by alexcrichton** [comment]
Ah yeah that'd be it! Basically some `#[cfg]` directives to make sure wasm32 doesn't try to use the unix implementation. The wasm-specific functions would likely just return an error saying "unsupported" rather than actually having an implementation.

**Comment by mpizenberg** [comment]
So I've managed to make it compile by removing the filetime dependency (temporarily) and by adding `target_arch = "wasm32"` cfg at some places. You can see the corresponding commit in this branch: https://github.com/mpizenberg/tar-rs/tree/wasm.

By using my local `tar = { path = "/home/matthieu/temp/rust/tar-rs" }` as dependency in this minimal [wasm-tar][wasm-tar] example, it is now compiling. It does not seem to work however. It is supposed to list the entries names, but the iteration loop is empty (no entry in the list somehow).

[wasm-tar]: https://github.com/mpizenberg/wasm-tar

**Comment by alexcrichton** [comment]
Good progress! I think we probably don't want to make `filetime` optional just yet and we'll want to get that working on wasm, but it's fine for an intermediate state. As to why it's not listing anything I'm not entirely sure :(

**Comment by mpizenberg** [comment]
Seems to be working now ;)

I was having some issues due to unexpected JS behavior ^^. All fixed now (not committed yet). I managed to keep the filetime dependency so I'll be doing some commit history cleaning and a PR for each crate, filetime and tar-rs, tomorrow I think.
