### ISSUE TITLE
Bumping tar crate version and changing edition at the same time breaks compatibility with stable rust

### ISSUE THREAD

**Issue by mbelop** [alexcrichton/tar-rs#194]
Hi,

I'd like to draw your attention to the fact that migrating to 2018 edition in https://github.com/alexcrichton/tar-rs/commit/5a52101460b0aa4fd8e95d12aa1413081c51b5ba and then bumping just the patchlevel part of the version has sent ripples across our build infrastructure that uses stable rust 1.29.2.  Perhaps a wiser move would've been to bump the minor (i.e. going to 0.5.0).

Nevertheless, thank you for your hard work, but please keep in mind that it should not make you entitled to disrespect other people's efforts.

With kind regards,
Mike

**Comment by alexcrichton** [comment]
Thanks for the report but the policy of the crates I maintain is to support the past two stable versions of rust on the latest release.
