### ISSUE TITLE
Remove test tarballs from published crate

### ISSUE THREAD

**Issue by pylaligand** [alexcrichton/tar-rs#196]
They don't seem to be useful for external usage.

**Comment by cramertj** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
I probably won't get around to this myself, but a PR is always welcome to do so!

**Comment by cramertj** [comment]
Sure-- I'll open one. Would you have a moment to publish shortly thereafter?

**Comment by cramertj** [comment]
Opened #197
