### ISSUE TITLE
BSD compat misses permissions on dirs?

### ISSUE THREAD

**Issue by rbtcollins** [alexcrichton/tar-rs#200]
#183 added a mode set to directories (which will cause extraction failures for readonly directories per #134, but thats a different, open ticket :P) - but didn't also add it for BSD tars?

```
        // Old BSD-tar compatibility.
        // Names that have a trailing slash should be treated as a directory.
        // Only applies to old headers.
        if self.header.as_ustar().is_none() && self.path_bytes().ends_with(b"/") {
            return self.unpack_dir(dst);
        }
```

Did old headers not have modes? Even if this is correct, it *looks* incorrect - would you object to me consolidating the code so that the mode check is still applied - its conditional, which should mean it will be skipped in this case if the archive can't represent modes, but would avoid puzzled faces from other code readers ;).

**Comment by alexcrichton** [comment]
I think consolidation is fine here. Extracting directories was added really late in the history of this crate so it may just be a misfeature. It's fine to update w/e is necessary to get it working

**Comment by rbtcollins** [comment]
Fixed in the Entry::Unpacked patch.
