### ISSUE TITLE
Do you need BufReader/BufWriter?

### ISSUE THREAD

**Issue by newpavlov** [alexcrichton/tar-rs#208]
README examples pass input file directly without any buffering and it seems a bit strange. Does this crate perform buffering internally? If so, it will be useful to add a note about it, otherwise I think examples should use `BufReader`/`BufWriter`.

**Comment by alexcrichton** [comment]
No buffering is performed by this crate, but you'll probably want to profile locally to see if you need internal buffering. The crate should work either way though!
