### ISSUE TITLE
Support for `Seek` trait

### ISSUE THREAD

**Issue by roman-holovin** [alexcrichton/tar-rs#218]
As far as I understand, `Archive::skip` is using `read` to skip over file contents. 
Is it possible to require `Read + Seek` and use `seek` to move through the input?

**Comment by alexcrichton** [comment]
Thanks for the report! I originally had `Read` and `Seek` but preferred to only require `Read`. Ideally we'd use some form of specialization for using `seek` where we can, but unfortunately that's not easily done right now.

**Comment by roman-holovin** [comment]
>I originally had Read and Seek but preferred to only require `Read`

Can you describe reasoning or link the discussion? I would like to read that.

>unfortunately that's not easily done right now.

Is there missing feature in compiler to do so? I've tried to modify slightly to require both `Read` and `Seek`, but it seems that is not something `rustc` can do now.

Can it be done with the separate API for now, while the common one is not available? And deprecate it latter.

**Comment by fermeise** [comment]
In our project we have a use case where we need to read the metadata of a tar archive with large file entries (>10 GB). Adding support for `Seek` would allow us to reduce the runtime from minutes down to milliseconds.

I've added a PR with a proposal that adds support for readers that implement `Seek` while maintaining compatibility with readers that don't. Would you consider a change like this? Any alternative proposals?
