### ISSUE TITLE
export internals for use in async-tar

### ISSUE THREAD

**Issue by danieleades** [alexcrichton/tar-rs#255]
[async-tar](https://github.com/dignifiedquire/async-tar) is in large part a copy-paste of the internals of this crate. Over time the implementations are drifting apart (for example `async-tar` apparently supports `redox` as a target).

this seems a bit daft to me. I wanted to gauge whether there was any appetite for refactoring this crate so that some of the internals could be imported in `async-tar` instead of being copied.

for example the `header.rs` implementation is damn near identical (see #254)

**Comment by alexcrichton** [comment]
Sorry I don't know much about `async-tar` or the history there. I think it's fine to export more functionality from this crate but I would still want a well-designed API with pieces that are thought through well and make sense. I don't want to "just make everything `pub`", for example.

**Comment by danieleades** [comment]
> Sorry I don't know much about `async-tar` or the history there. I think it's fine to export more functionality from this crate but I would still want a well-designed API with pieces that are thought through well and make sense. I don't want to "just make everything `pub`", for example.

I was thinking more along the lines of splitting out some of the types into a separate crate and publishing that, rather than just adding `pub`s everywhere

**Comment by alexcrichton** [comment]
Personally I would prefer to not maintain a separate crate for that purpose.

**Comment by danieleades** [comment]
It would be a separate crate in the same repo, as a workspace. But I understand the reservations
