### ISSUE TITLE
`no_std` compliance?

### ISSUE THREAD

**Issue by phip1611** [alexcrichton/tar-rs#264]
Are there any goals to make this library `no_std`-compliant? The `std`-related part, such as filenames, could be part of a default `std`-cargo module, while the core parsing of the bytes in the tar format should be `no_std`-compliant. I could try to assist you with a PR to build this into the crate.

Because this would probably be a bigger change, I'd like to request approval of the general idea or thoughts about it.

If not, I could use this crate and transform it to a smaller, new one, that is `no_std`-compatible and use as much source as possible - of course I would mention the original authors according to the license.

**Comment by alexcrichton** [comment]
At this time, no, there's no goals to make this work with just the `core` crate and without the `std` crate.
