### ISSUE TITLE
tar-rs doesn't recover the mtime of the unpacked files

### ISSUE THREAD

**Issue by simnalamburt** [alexcrichton/tar-rs#27]
Current implementation of `tar-rs` does recover the file permission of the unpacked file but *not* for the `mtime`. `mtime` doesn't matter for most cases but sometime [it does][twitter].

target: https://github.com/alexcrichton/tar-rs/blob/68c7581006d829f79623846fcb303ef1a1cec178/src/lib.rs#L858
```rust
    fn unpack2(&mut self, dst: &Path) -> io::Result<()> {
        try!(io::copy(self, &mut try!(fs::File::create(dst))));

        // HERE will be the good position to restore mtime of the unpacked file.
        try!(set_perms(dst, try!(self.header().mode())));
        return Ok(());

        #[cfg(unix)]
        fn set_perms(dst: &Path, mode: u32) -> io::Result<()> {
            use std::os::unix::raw;
```

Unfortunately, the function [`set_file_times`][t] is unstable yet. So we may have to embed the function body of [`set_file_times`][t] into `tar-rs` just like you did with the [`cargo`][c].

##### Option A: Use `utimes` for unix, and `SetFileTime` for windows.
:+1: : I'll reuse the patch which you made before.
:-1: : Additional dependencies (`winapi` and `kernel32-sys`) will be added to `tar-rs` for windows.

###### Option B: Use [`utime`][u] for both unix and windows.
:+1: : No additional dependency.
:-1: : [`utime`][u] is [obsoleted][u2] by POSIX.1-2008.

I'm going to PR this. Do you agree with this plan? Which option do you prefer?

[twitter]: https://twitter.com/simnalamburt/status/625013067835813888
[t]: http://doc.rust-lang.org/stable/std/fs/fn.set_file_times.html
[c]: https://github.com/rust-lang/cargo/commit/23762e4586#diff-b99116b24344572ec62bb4702e213e50R119
[u]: http://doc.rust-lang.org/libc/libc/funcs/posix88/unistd/fn.utime.html
[u2]: http://man7.org/linux/man-pages/man2/utime.2.html#CONFORMING_TO

**Comment by alexcrichton** [comment]
Yeah I just want to make sure this library still compiles on stable, and I'd prefer to use Windows APIs wherever possible. Ideally the `utimes`/`SetFileTime` split would be in a separate crate on crates.io so both this and Cargo could share the implementation.

**Comment by simnalamburt** [comment]
Then let me make a new crate which only changes the atime/mtime of the file.
