### ISSUE TITLE
How to use list.rs in the example

### ISSUE THREAD

**Issue by QuintinTao** [alexcrichton/tar-rs#275]
please tell me how use this example  list.rs.

I run it in the Linux.  compiled it into a executable file.
./list .  it was waiting for my input. I don't know what should I input. So  I put a tar in the same director of the file list.
![image](https://user-images.githubusercontent.com/72123724/145786556-6eb3e470-d892-40a5-8dd5-b923eaf686b5.png)

**Comment by QuintinTao** [comment]
And what is the stdin？ what should I input？
![image](https://user-images.githubusercontent.com/72123724/145787083-4ba615e5-2fa9-4170-8150-aac97cb39bd6.png)

**Comment by p-inks** [comment]
You can try like `cargo run --example list < example.tar`  
For more info see [here](https://en.wikipedia.org/wiki/Standard_streams)

**Comment by alexcrichton** [comment]
Yes what @p-inks mentioned should work.

**Comment by QuintinTao** [comment]
> You can try like `cargo run --example list < example.tar` For more info see [here](https://en.wikipedia.org/wiki/Standard_streams)

3q for your help.it does work.

**Comment by QuintinTao** [comment]
> Yes what @p-inks mentioned should work.

3q
