### ISSUE TITLE
[Bug?] numeric field did not have utf-8 text

### ISSUE THREAD

**Issue by MordechaiHadad** [alexcrichton/tar-rs#278]
# Environment
- Operating System: `Linux 5.10.16.3-microsoft-standard-WSL2`
- Rust Version: `1.58.1`

# The Issue
I am trying to get a file using a for loop with archive.entries(), when i match Result<Entry<File>> i get an error saying:
```
numeric field did not have utf-8 text: ��Qr�
 when getting cksum for �
 ```
 
 also i noticed that it only runs once even tho the `tar.gz` file contains multiple files
 The code:
 ```rs
    let mut archive = tar::Archive::new(file);
     for file in archive.entries()? {
        match file {
            Ok(value) => println!("got here"),
            Err(error) => println!("{error}") // Here is where i get the error from
        }
    }
 ```
btw I also checked maybe it was a problem with the file itself that i pushed to `Archive::new()` but it was made correctly

**Comment by alexcrichton** [comment]
This sounds like the archive is corrupt or you're perhaps not decompressing it before you're parsing it.

**Comment by MordechaiHadad** [comment]
> This sounds like the archive is corrupt or you're perhaps not decompressing it before you're parsing it.

By archive do you mean the tar::Archive instance i made or the file itself?
If the file I used tar and it decompressed with no issues at all.

**Comment by MordechaiHadad** [comment]
> Given the amount of information I have here I don't know. When you call `tar::Archive::new(file)` I don't know what `file` is. If that source of I/O contains a gzip-compressed file, that's invalid. The `tar::Archive::new` constructor expects a stream of uncompressed data for the archive.

Here is basically what i do:
```rs
use std::fs::File;
use tar::Archive;

fn main() {
 let file = File::open("nvim.tar.gz").unwrap();
    let mut a = Archive::new(file);

    for file in a.entries().unwrap() {
        match file {
            Ok(value) => println!("Got here"),
            Err(error) => println!("{error}")
        }

    
    }
}
```
and this is what nvim.tar.gz is downloaded from [https://github.com/neovim/neovim/releases/download/v0.6.1/nvim-linux64.tar.gz](url) (I also renamed it to nvim.tar.gz)

**Comment by isaackd** [comment]
To use your current code you'll need to decompress the file first and then refer to that decompressed file in the code.
If you want to decompress the file in code before reading the archive you can use a crate like [flate2](https://crates.io/crates/flate2):
```rust
use std::fs::File;
use tar::Archive;
use flate2::read::GzDecoder;

fn main() {
    let file = File::open("nvim.tar.gz").unwrap();
    let decompress_stream = GzDecoder::new(file);
    let mut a = Archive::new(decompress_stream);

    for file in a.entries().unwrap() {
        match file {
            Ok(value) => println!("Got here"),
            Err(error) => println!("{error}")
        }
    }
}
```

**Comment by MordechaiHadad** [comment]
@isaackd you are right, I accidentally thought it also accepted a .tar.gz file instead of only a .tar.
Apologies.
