### ISSUE TITLE
Long loop when decompressing this tar

### ISSUE THREAD

**Issue by kszlim** [alexcrichton/tar-rs#291]
I'm trying to incrementally decompress this tar.gz, and the program seems to hang after iterating over the second element.

Simply looping over the entries will result in an infinite loop (regular CLI tools are able to decompress this archive successfully). I've tested tar-rs with both `libflate` and `flate2` and it results in an infinite loop.

```rust
use libflate::gzip::Decoder;
use tar::Archive;
use std::fs::File;

fn main() {
    load_order_book_compressed("data.tar.gz");
}

fn load_order_book_compressed(archive_path: &str) {
    let tar = Decoder::new(File::open(archive_path).unwrap()).unwrap();
    let mut archive = Archive::new(tar);
    let mut entries = archive.entries().ok().unwrap();
    for entry in entries {
        dbg!(entry.unwrap().header());
    }
}
```
https://drive.google.com/file/d/1WWw10vbNGU_2J04KujwecTMwr8DtLqNx/view?usp=sharing

**Comment by kszlim** [comment]
I did more testing, and it's actually not looping infinitely, it seems like I loop over the two entries nearly immediately, and the library takes a long time to determine/fail out of the third nonexistent entry.

You'll want to test this in --release mode or it will take a long time to reproduce.

**Comment by alexcrichton** [comment]
To confirm, are you sure the loop is in this library as opposed to the gzip layer? If possible can the two be separated?

**Comment by kszlim** [comment]
I think so, though I'm not 100% sure, as I did try with `flate2` and `libflate` with the same results, I even tried various gzip backends in `flate2`.

**Comment by alexcrichton** [comment]
I tested this locally and I believe that there's no issue here. The tarball has, as you noticed, a 13GB file in it so decompressing that and seeking is slow, as is to be expected. I don't think there's an infinite loop, it just takes awhile to process the file. Note that debug mode is going to be even slower in this case as well.
