### ISSUE TITLE
Alternative append API

### ISSUE THREAD

**Issue by piegamesde** [alexcrichton/tar-rs#304]
At the moment in the API, I have to provide a `Read` and then the `append` function(s) will `io::copy` over the bytes in one go. This is fine for many use cases, but not always desirable.

As an alternative that may work better in some cases, I propose having an API that instead of taking a `Read` returns a `Write`. One can then write into there in order to write into the archive. Lifetimes are use to enforce that no other functions can be called on the archive in the meantime, and the `Drop` implementation takes care of finalizing the file (i.e. add the padding).

**Comment by lynzrand** [comment]
I'm researching on a seekable compressed TAR format, and I would like to see this API too, so that I can write the TAR header and body separately and compress them in different compression blocks.

**Comment by sunshowers** [comment]
Note that providing a handle that implements `Write` is strictly more generic than having a method that accepts `Read`, because [`std::io::copy`](https://doc.rust-lang.org/stable/std/io/fn.copy.html) can be used to transfer data from any reader into a writer.
