### ISSUE TITLE
Empty symbolic link contents

### ISSUE THREAD

**Issue by mbrt** [alexcrichton/tar-rs#41]
Reading a symbolic link inside a tar file results in an empty file. The expected behavior is to get the path of the linked file (like the `readlink` linux command).

PR #40 demonstrate the problem with a new test.

**Comment by alexcrichton** [comment]
Thanks for the report! I ended up tweaking the test as well, but should be good to go now. Let me know if you run into anything else!

**Comment by mbrt** [comment]
The new test you've added now does not fail, however my original one still fails. If you use the `Read` trait, the contents is still empty. I see it because in my code I don't use the `unpack` method of `Entry`, but the `Read` trait impl.

**Comment by alexcrichton** [comment]
Ah yeah that's to be expected actually, the `Read` implementation for `Entry` just reads the contents of the archive rather than the actual file that it points to, so there's no way that the symbolic link behavior could happen as part of this crate, you'll have to extract to the filesystem first and then let that resolve symlinks (or keep track of the info in a side table elsewhere.

**Comment by mbrt** [comment]
Of course the symbolic link behavior is not working. My expectation when reading is instead to get the symbolic link *actual* contents, that is the path to the linked file (and not the contents of the file). I'm not sure if it's clear.

In the test case it's the difference between `cat lnk` (that outputs `file_contents`, the contents of `file`) and `readlink lnk` (that outputs `file`).

**Comment by alexcrichton** [comment]
Ah currently that can be discovered via `header.link_name()`. I think there's a separate GNU extension where the contents read are the full link name (if it's too long to fit in the header), but for now I'd prefer the `Entry` type's `Read` implementation to read precisely what's listed in the archive (e.g. no munging or manifesting new data)

**Comment by mbrt** [comment]
I'm fine with that. I can use `header.link_name()` instead of `Read` in the symlink case. Ok, everything is fixed for me! When you are ready, please update the crate! Thanks

**Comment by alexcrichton** [comment]
Yeah there's some breakage on Windows that I wanna work through first, but once that's all in order I'll publish a new version.
