### ISSUE TITLE
Lifetime requirements backwards incompatibility

### ISSUE THREAD

**Issue by aidanhs** [alexcrichton/tar-rs#43]
```
extern crate tar;

use std::fs;
use tar::Archive;

fn main() {
    let tnames = vec!["a", "b", "c"];

    let ars: Vec<Archive<fs::File>> = tnames.iter().map(|tname| {
        let file = fs::File::open(tname).unwrap();
        Archive::new(file)
    }).collect();
    let mut arfiless: Vec<Vec<tar::File<fs::File>>> = ars.iter().zip(tnames).map(|(ar, tname)| {
        let arfiles: Vec<_> = ar.files().unwrap().map(|res| res.unwrap()).collect();
        arfiles
    }).collect();

    let mut arheadmaps: Vec<_> =
        arfiless.iter_mut().map(|arfiles| xx(arfiles)).collect();
}

fn xx<'a, 'b: 'a>(arfiles: &'a mut Vec<tar::File<'a, fs::File>>) {

}
```
```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling tar v0.3.2 (file:///space/aidanhs/rust/tar-rs)
   Compiling dayer v0.1.1 (file:///space/aidanhs/rust/dayer)
src/main.rs:19:9: 19:17 error: `arfiless` does not live long enough
src/main.rs:19         arfiless.iter_mut().map(|arfiles| xx(arfiles)).collect();
                       ^~~~~~~~
src/main.rs:12:18: 20:2 note: reference must be valid for the block suffix following statement 1 at 12:17...
src/main.rs:12     }).collect();
src/main.rs:13     let mut arfiless: Vec<Vec<tar::File<fs::File>>> = ars.iter().zip(tnames).map(|(ar, tname)| {
src/main.rs:14         let arfiles: Vec<_> = ar.files().unwrap().map(|res| res.unwrap()).collect();
src/main.rs:15         arfiles
src/main.rs:16     }).collect();
src/main.rs:17 
               ...
src/main.rs:16:18: 20:2 note: ...but borrowed value is only valid for the block suffix following statement 2 at 16:17
src/main.rs:16     }).collect();
src/main.rs:17 
src/main.rs:18     let mut arheadmaps: Vec<_> =
src/main.rs:19         arfiless.iter_mut().map(|arfiles| xx(arfiles)).collect();
src/main.rs:20 }
error: aborting due to previous error
Could not compile `dayer`.

To learn more, run the command again with --verbose.
```

This breaks after https://github.com/alexcrichton/tar-rs/commit/71b60399f0ce5d20765e81441b1f3d79255e1a48

Easily fixable by adding changing `'a, fs::File` to `'b, fs::File` on `xx`, but it worked before.

**Comment by aidanhs** [comment]
```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling tar v0.3.2 (file:///space/ahobsons/rust/tar-rs)
   Compiling dayer v0.1.1 (file:///space/ahobsons/rust/dayer)
src/main.rs:19:9: 19:17 error: `arfiless` does not live long enough
src/main.rs:19         arfiless.iter_mut().map(|arfiles| xx(arfiles)).collect();
                       ^~~~~~~~
src/main.rs:12:18: 20:2 note: reference must be valid for the block suffix following statement 1 at 12:17...
src/main.rs:12     }).collect();
src/main.rs:13     let mut arfiless: Vec<Vec<tar::File<fs::File>>> = ars.iter().zip(tnames).map(|(ar, tname)| {
src/main.rs:14         let arfiles: Vec<_> = ar.files().unwrap().map(|res| res.unwrap()).collect();
src/main.rs:15         arfiles
src/main.rs:16     }).collect();
src/main.rs:17 
               ...
src/main.rs:16:18: 20:2 note: ...but borrowed value is only valid for the block suffix following statement 2 at 16:17
src/main.rs:16     }).collect();
src/main.rs:17 
src/main.rs:18     let mut arheadmaps: Vec<_> =
src/main.rs:19         arfiless.iter_mut().map(|arfiles| xx(arfiles)).collect();
src/main.rs:20 }
error: aborting due to previous error
Could not compile `dayer`.

To learn more, run the command again with --verbose.
```

**Comment by aidanhs** [comment]
Simpler:
```
extern crate tar;

use std::fs;
use tar::Archive;

fn main() {
    let file = fs::File::open("a").unwrap();
    let ar = Archive::new(file);
    let arfiles: Vec<tar::File<fs::File>> = ar.files().unwrap().map(|res| res.unwrap()).collect();
    xx(&arfiles);
}

fn xx<'a>(arfiles: &'a Vec<tar::File<'a, fs::File>>) {}
```

**Comment by aidanhs** [comment]
In fact, the error "`arfiles` does not live long enough" is really not the error I would expect, given that the following definition of `xx` allows it to compile:
```
fn xx<'a, 'b: 'a>(arfiles: &'a Vec<tar::File<'b, fs::File>>) {}
```
Typically when rust is unable to satisfy function lifetime parameters it says (IIRC) something like "unable to satisfy lifetime bounds of X" and you now have a clue that you've done something wrong with function lifetime parameters.

**Comment by alexcrichton** [comment]
Hm OK, I tracked this down and it seems to be because the the "seek" operation in an `Entry` was changed from a `fn(Foo)` to a `Box<Fn(Foo)>` to handle some extra captured data, and that addition of a destructor ended up triggering what I can only presume are the dropck rules.

I'll see if I can't find a way to make that just a plain `fn` without unsafe code...

**Comment by alexcrichton** [comment]
Hm ok, so after thinking a little more about this I think there's not much that can be done here. This is an unfortunate interaction with dropck but overall I think it's not too bad of a breaking change or too bad to fix in practice. For now I'm gonna close this but let me know if there's any difficulty in upgrading!

This is certainly surprising to me in terms of backwards compatibility, and I'll try to keep an eye out for things like this in the future!

**Comment by aidanhs** [comment]
Thanks for the clear explanation! It does makes sense to me that adding destructors could influence lifetimes (because, if I'm understanding correctly, you now have an extra lifetime that needs to be tracked because a fn without a box does not have any lifetime).

However, I'm still a little perplexed around the exact cause of the error. Reading https://github.com/rust-lang/rfcs/blob/master/text/0192-bounds-on-object-and-generic-types.md#lifetime-bounds-on-parameters (specifically "for any lifetime `'a`, `'a` outlives `'a`"), it seems to me that the lifetimes accepted by:
```
fn xx<'a, 'b: 'a>(x: &'a Vec<T1<'b, T2>>) {}
```
are a superset of those accepted by
```
fn xx<'a>(x: &'a Vec<T1<'a, T2>>) {}
```
because `'a` is a valid lifetime for `'b` in `'b: 'a`?

**Comment by aidanhs** [comment]
Sorry, I shouldn't write comments when tired! I was looking at it from the wrong direction!

The problem is to do with my current lifetime rules being too strict and having to relax them, not the other way around which is what I mistakenly wrote the comment above based on.

Is there any reading you can recommend on the dropck rules etc? Or is it just the normal case of hunting in the rfcs repo?

**Comment by alexcrichton** [comment]
Ah yeah unfortunately I don't know of any better documents other than what's in the rfcs repo :(
