### ISSUE TITLE
Long paths are truncated

### ISSUE THREAD

**Issue by mbrt** [alexcrichton/tar-rs#44]
Here is a tar file with a long path: [long_path.zip](https://github.com/alexcrichton/tar-rs/files/68313/long_path.zip) (zipped because github don't like tars).

Listing the content with `tar -tf long_path.tar` gives:
```
home/
home/michele/
home/michele/Documenti/
home/michele/Documenti/Development/
home/michele/Documenti/Development/Progetti/
home/michele/Documenti/Development/Progetti/MetaCloudExperiment/
home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/
home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/
home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/BuildTools/
home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/BuildTools/WixIncludeMake/
home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/BuildTools/WixIncludeMake/Program.cs
```

Listing the contents with this snippet:
```rust
let file = File::open("long_path.tar").unwrap();
let mut tar = Archive::new(file);
for file in tar.files_mut().unwrap() {
    if let Ok(f) = file {
        println!("{:?}", f.header().path().unwrap())
    }
}
```

Gives the following result:
```
"home/michele/"
"home/michele/Documenti/"
"home/michele/Documenti/Development/"
"home/michele/Documenti/Development/Progetti/"
"home/michele/Documenti/Development/Progetti/MetaCloudExperiment/"
"home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/"
"home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/"
"home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/BuildTools/"
"././@LongLink"
"home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/BuildTools/WixIn"
"././@LongLink"
"home/michele/Documenti/Development/Progetti/MetaCloudExperiment/Reference/duplicati/BuildTools/WixIn"
```

Truncating paths and adding those `././@LongLink` entries.

**Comment by aidanhs** [comment]
This is the GNU extension to the tar format to support long (>255 chars) path names. See http://stackoverflow.com/questions/2078778/what-exactly-is-the-gnu-tar-longlink-trick

I might be able to implement this in a couple of days if nobody else gets there first.

**Comment by alexcrichton** [comment]
Hm yeah this definitely doesn't handle `././@LongLink` yet, although it looks like a simple enough format at least. It may be somewhat difficult to add support for this, but I think the best way may be to add some sort of caching to the iterator which indicates what the name of the *next* file is and then add a method `Entry::path` which is distinct from `Header::path`. It may also be prudent to rename `Header::path` to `Header::raw_path` or something like that to indicate that the path returned there is not guaranteed to be the correct one.

It'd also probably be good to add support for writing this form of archive entry as well, and that part should be extra-easy as it's just writing more data!

**Comment by aidanhs** [comment]
That would work, but the nice thing about `entries()` and `entries_mut()` is you can predict memory usage. If you cache a path in memory (which would be necessary for non-seekable files) it becomes impossible to iterate over a tar with this library without potentially hitting memory exhaustion on a malformed/malicious tar.

My proposal would be to leave the `entries` iterator as a low level API and build a 'higher level' iterator on top of that returning `FileEntry`s (or something) which would hold any 'prefix' entry headers and data (LongLink, posix header) in memory. You could then have appropriate `FileEntry::path` etc methods which would give preference to the GNU extensions/posix headers if present, and a `FileEntry::entries` method to get at the low level data if you need it.

**Comment by alexcrichton** [comment]
Yeah that's definitely a downside, but it has the benefit of convenience. It's likely that some reasonable limits could be put in place (e.g. no path names > 1MB) to prevent automatic malicious exhaustion, and I think that this could also have a `.raw_entries()` iterator.

To me it at least seems like the right default would be to handle archives like this (as it's probably what other implementations do) but still allow lowering down to the raw representation if it's not desired. I do think though that having an iterator adaptor may work well in terms of an implementation detail.

How's that sound?

**Comment by mbrt** [comment]
I agree with you. I think this has the benefit of convenience.

----- Messaggio originale -----
Da: "Alex Crichton" <notifications@github.com>
Inviato: ‎21/‎12/‎2015 21:52
A: "alexcrichton/tar-rs" <tar-rs@noreply.github.com>
Cc: "Michele Bertasi" <michele.bertasi@gmail.com>
Oggetto: Re: [tar-rs] Long paths are truncated (#44)

Yeah that's definitely a downside, but it has the benefit of convenience. It's likely that some reasonable limits could be put in place (e.g. no path names > 1MB) to prevent automatic malicious exhaustion, and I think that this could also have a .raw_entries() iterator.
To me it at least seems like the right default would be to handle archives like this (as it's probably what other implementations do) but still allow lowering down to the raw representation if it's not desired. I do think though that having an iterator adaptor may work well in terms of an implementation detail.
How's that sound?

**Comment by aidanhs** [comment]
I definitely agree that there should be *some* high level api which just handles it all for you when you don't really care about the possibility of memory exhaustion, i.e. a new `Archive::file_entries` method. My focus is just on leaving `Archive::entries` as it is - it does exactly what it says on the tin, iterates over all 'entries' of a tar achive, be it an actual file or directory entry, or a posix extended header.

If you have two different methods (low and high level) then there's no need to talk about a default.

**Comment by aidanhs** [comment]
I'll come up with an implementation today to demonstrate what I mean, as I'm not sure I'm explaining very well.

**Comment by alexcrichton** [comment]
@aidanhs hm yeah that does actually make sense, and on one hand I do kinda like how low-level the library is currently.

I've got some stuff I've also been working on for this locally, so let me see if I can't push it up soon to see if it meshes with what you're thinking as well.

**Comment by mbrt** [comment]
I've done my version directly in a library I'm developing, to test the usage. You can see it in [this file](https://github.com/mbrt/ruplicity/blob/60c427b0a5d7d5d9ea0e5c000fbf356d365faa1d/src/tarext.rs#L25).

Note that I've ported your PR #45 with a couple of fixes:
* at [line 57](https://github.com/mbrt/ruplicity/blob/60c427b0a5d7d5d9ea0e5c000fbf356d365faa1d/src/tarext.rs#L57) I've used `Vec::resize` and `Read::read` instead of `Read::read_to_end`, because the latter can possibly increase the allocation more than the capacity of the vector, and so a malicious tar can cause crazy allocations;
* at [line 65](https://github.com/mbrt/ruplicity/blob/60c427b0a5d7d5d9ea0e5c000fbf356d365faa1d/src/tarext.rs#L65) I've removed trailing '\0' chars that can occur at the end of the path (null terminators are optional but can occur).

**Comment by aidanhs** [comment]
@mbrt do you have any plans for posix headers? Or are you only concerned with GNU for now?

**Comment by mbrt** [comment]
@aidanhs Hard to know. My concern is to make my library to work with all possible duplicity backups. The only format used is GNU, as far as I know, but I can be wrong. However GNU format support will be not complete even when this issue will be closed (long links and sparse files are missing for example). So, I think I will concentrate only at GNU for now.
