### ISSUE TITLE
Handle pax_global_header

### ISSUE THREAD

**Issue by dbrgn** [alexcrichton/tar-rs#48]
With the released version (0.3.2) of tar-rs, when unpacking a Github `.tar.gz`, the directory contains a file called `pax_global_header`. See https://github.com/backdrop-ops/contrib/issues/55.

So I tried the current master, because I saw that you worked on headers. Now I get the following error:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
repr: Custom(Custom { kind: Other, error: TarError {
desc: "failed to unpacked `foo/pax_global_header`",
io: Error { repr: Custom(Custom { kind: Other,
error: StringError("unknown file type 0x67") }) } } }) }', ../src/libcore/result.rs:738
```

I'm not sure how to deal with that, is some code missing to handle this header?

**Comment by dbrgn** [comment]
Found it in the tar specs: https://www.gnu.org/software/tar/manual/html_node/Standard.html (`XGLTYPE`). I'll try to come up with a PR.

**Comment by alexcrichton** [comment]
A very good point! I recently looked a bit more into the various flavors of archives that can exist, and I'm thinking of tweaking the APIs here and there to support all the flavors I could find (including pax here).

I hope to send a PR soon!

**Comment by SoloKarma** [comment]
https://github.com/alexcrichton/tar-rs/issues/48
