### ISSUE TITLE
Infinite entries iteration on error

### ISSUE THREAD

**Issue by mbrt** [alexcrichton/tar-rs#53]
There is a regression with the current 0.4 version. If, during the entries iteration an error occurs, the iteration goes on forever, returning always `Some(Err(_))`.

I've attached a 
[test file](https://github.com/alexcrichton/tar-rs/files/101242/loop.zip) demonstrating the issue.

Minimal snippet to reproduce:
```
let file = File::open("loop.tar");
let mut tar = Archive::new(file);
for _entry in tar.entries() { }
```

The error is caused by the last entry in the tar, (which is a non-UTF8 path, but I don't think it matters). With this test:
```
    let file = File::open("loop.tar").unwrap();
    let mut tar = Archive::new(file);
    for entry in tar.entries().unwrap() {
        match entry {
            Ok(e) => {
                println!("{:?}", e.path());
            }
            Err(e) => {
                println!("{:?}", e);
            }
        }
    }
```

I can say that the paths are correctly iterated, but at the end, the error is reported forever:
```
...
Ok("snapshot/two_hardlinked_files1")
Ok("snapshot/two_hardlinked_files2")
Ok("snapshot/\u{62b}\u{fffd}Wb\u{fffd}\u{fffd}]\u{fffd}\u{fffd}\u{15}v*\u{fffd}\u{f}!\u{fffd}>\u{fffd}Y\u{fffd}\u{fffd}\u{fffd}\u{fffd}p\u{fffd}\u{fffd}\u{13}k\u{1d}\u{fffd}\u{fffd}\u{fffd}e\u{fffd}U\u{fffd}\u{fffd}UV\u{fffd}\u{fffd}\u{fffd}4\u{fffd}\u{fffd}X\u{3}\u{fffd}\u{7}s\u{39e}\u{fffd}\u{fffd}4\u{4}\u{fffd}\u{17} \u{fffd}\u{fffd}\u{fffd}\u{fffd}\u{62c}\u{685}\u{fffd}KvC\u{fffd}#\u{fffd}\u{fffd}\u{fffd}\u{277}\u{fffd}_\u{f}\u{fffd}g\u{fffd}B\u{11}<=^\u{fffd}M\u{13}\u{fffd}c\u{fffd}\u{fffd}|*\"/\'^$@#!(){}?+ ~` ")
Error { repr: Custom(Custom { kind: Other, error: StringError("failed to read entire block") }) }
Error { repr: Custom(Custom { kind: Other, error: StringError("failed to read entire block") }) }
...
```

I've done some preliminary analysis and it seems that some done flag is missing, because `next_entry_raw` continuously returns an `Ok(Error(_))` when it is not able to read data from the header, at `archive.rs: 220`.

**Comment by alexcrichton** [comment]
Gah oops, forgot to indeed set a `done` flag.

Out of curiosity, are you sure this is a valid archive? It looks like it's OK except for that it doesn't end with the standard 1 kilobyte of nul bytes. I'm curious if this was created by a tool and if so if that's actually an accepted archive format.

**Comment by mbrt** [comment]
It seems a valid tar, since `tar -tf loop.tar > /dev/null` exits with a 0 code. The file is taken from a valid duplicity backup. So it has been generated by python [tarfile](https://docs.python.org/2/library/tarfile.html) library!

**Comment by alexcrichton** [comment]
Hm interesting... The tar format requires that archives are terminated with two blocks of all 0s (a block is 512 bytes), and the python tarfile library [has a function for doing this](https://docs.python.org/2/library/tarfile.html#tarfile.TarFile.close), so it looks like it may be a bug in duplicity that this isn't done.

In that case it may be best to handle those kinds of archives and just return `None` saying that we're at the end of the archive.

**Comment by mbrt** [comment]
It seems like a bug indeed! I don't know if it's better to return an error or to simply terminate the iteration. Maybe the latter solution is more ergonomic, since who cares about those ending blocks? :) In any case it's your option. Both ways are fine for me!

----- Messaggio originale -----
Da: "Alex Crichton" <notifications@github.com>
Inviato: ‎22/‎01/‎2016 21:35
A: "alexcrichton/tar-rs" <tar-rs@noreply.github.com>
Cc: "Michele Bertasi" <michele.bertasi@gmail.com>
Oggetto: Re: [tar-rs] Infinite entries iteration on error (#53)

Hm interesting... The tar format requires that archives are terminated with two blocks of all 0s (a block is 512 bytes), and the python tarfile library has a function for doing this, so it looks like it may be a bug in duplicity that this isn't done.
In that case it may be best to handle those kinds of archives and just return None saying that we're at the end of the archive.

**Comment by alexcrichton** [comment]
Hm ok for now I think I'll continue to emit an error (in an effort to be "more standard compliant"), but if you would like a better error value or something like that to be returned please just let me know!
