### ISSUE TITLE
doc: mention of variable `into` for method `unpack`

### ISSUE THREAD

**Issue by 0X1A** [alexcrichton/tar-rs#54]
In the [documentation for unpack](http://alexcrichton.com/tar-rs/tar/struct.Archive.html#method.unpack) a variable `into` is referenced but is not listed in the function nor is it [in the source](http://alexcrichton.com/tar-rs/src/tar/archive.rs.html#87): 

"This operation is relatively sensitive in that it will not write files outside of the path specified by into." 

What is `into` in reference to?

**Comment by aidanhs** [comment]
Fairly sure that, should be `dst`, have opened a PR.
