### ISSUE TITLE
`.unpack` on an Archive should handle GNU extensions

### ISSUE THREAD

**Issue by aidanhs** [alexcrichton/tar-rs#56]
https://github.com/alexcrichton/tar-rs/blob/0cc93a7/src/archive.rs#L109

(someone hit this - https://users.rust-lang.org/t/tar-rs-failed-to-iterate-over-archive-when-unpacking-tar/4442)

**Comment by alexcrichton** [comment]
Oh that's actually an old TODO, this should be handled [by the `entries` iterator](https://github.com/alexcrichton/tar-rs/blob/master/src/archive.rs#L266) (the GNU extensions). I'll comment on that thread though.
