### ISSUE TITLE
Paths with backslash is replaced with slash

### ISSUE THREAD

**Issue by mbrt** [alexcrichton/tar-rs#57]
If a tar file contains a file with a backslash '\' in its path, it is replaced with a slash '/'. This however is incorrect in my opinion, because:
1. tar format says "separated by slashes", so any tar that assumes '\' to be a directory separator is malformed;
2. a file named "fo\o.txt" (with '\' intended literally a backslash and not an escape), becomes "fo/o.txt", i.e. a directory and a file within it).

I know that backslashes are problematic under windows. But this behavior is not correct under Linux.

**Comment by mbrt** [comment]
To be more explicit, my problem is not the `unpack` feature of `Entry`, but `path`, `path_bytes`, `link_name` and `link_name_bytes`.

**Comment by alexcrichton** [comment]
Yeah this behavior currently exists to handle buggy archives that were created on Windows long ago. The paths used to be encoded directly with `\` as a separator instead of `/`. I think this was mainly done for some old Cargo archives published, but there may not actually be any more of those in existence, so it may be time to just remove this logic.

**Comment by mbrt** [comment]
I think it's better.

**Comment by alexcrichton** [comment]
Ok, the commit mentioned here should take care of this, could you try it out and let me know if it works for you?

cc @aidanhs as well, not sure if you've run into this before as well

**Comment by mbrt** [comment]
Thanks. I've tested it and I found a regression in GNU long paths. The null terminator is appended in `Entry.path_bytes`, which didn't before. So, for example, `my/path` becomes `my/path\u{0}` if it is a long path.

The '\' chars are correctly preserved though.

**Comment by aidanhs** [comment]
@alexcrichton thanks for the ping, happily not an issue, I only deal with tar files created on linux.

**Comment by alexcrichton** [comment]
@mbrt oh hm it appears that those previously has `truncate` called on them which terminated at the first nul byte. In the case of a long path, however, there shouldn't be any nul bytes in the entry, right? Are you writing the long paths manually?

**Comment by mbrt** [comment]
@alexcrichton yeah, I'm pretty sure nul bytes shouldn't happen in the middle of a path. My test file has been created with standard `tar` under linux. You can find the tar [here](https://github.com/mbrt/ruplicity/blob/master/tests/long_path.tar).

In [ubuntu man](http://manpages.ubuntu.com/manpages/intrepid/man5/star.5.html) I found this, regarding long file names:
> The size is always non zero and denotes the length of the long file  name including  the  trailing null byte.

So, apparently a nul byte could be added at the end.

**Comment by alexcrichton** [comment]
Interesting! Ok I've pushed two more commits which I think should take care of that aspect as well, do they work for you @mbrt?

**Comment by mbrt** [comment]
Yep! Good to release for me. Thanks!

**Comment by alexcrichton** [comment]
Cool, published 0.4.4, thanks for the report and the testing!
