### ISSUE TITLE
Symlink targets are unnecessarily checked

### ISSUE THREAD

**Issue by tailhook** [alexcrichton/tar-rs#67]
I think it's fine to write any symlink to the archive, i.e. an absolute path or a relative path with `..`.

In my case, I'm trying to pack a symlink at `a/b/c` which points to `a/x/c`. With the current code, I can put neither relative nor absolute link to point to the location. The error I get:
```
paths in archives must not have `..`
```

**Comment by alexcrichton** [comment]
Oh is that validation code running on the destination of the symlink? That should definitely not be happening

**Comment by tailhook** [comment]
Yes. it's in [set_link_name](https://github.com/alexcrichton/tar-rs/blob/master/src/header.rs#L373) which is used both for original file name and for link destination.

**Comment by tailhook** [comment]
Thanks!
