### ISSUE TITLE
Adding Hidden "." Directories

### ISSUE THREAD

**Issue by mmstick** [alexcrichton/tar-rs#68]
I'm having a hard time figuring out how to add hidden directories to the tar archive. The directory structure of the tar that I am creating must contain all files within a "." directory of the tar archive, but I am at a loss as to how to create that directory in the tar. The `append_dir` method doesn't seem to accept "." as a valid input for the first argument, and the second argument seems to be ignored completely.

The directory structure must be as such:

```
control.tar
    |--> ./
         |--> control
         |--> md5sums
         |--> etc..
```

This also failes to create the "." directory, as it complains that there must be at least one component in the path:

``` rust
    let mut header = TarHeader::new_gnu();
    header.set_size(0);
    header.set_mode(CHMOD_BIN_OR_DIR);
    header.set_path(".").unwrap();
    header.set_entry_type(tar::EntryType::Directory);
    header.set_cksum();
    archive.append(&header, &mut io::empty()).unwrap();
```

**Comment by alexcrichton** [comment]
Oh it may be invalid not allowing a `.` entry, that validation logic should allow a path like that. Wanna send a PR to update that piece?

**Comment by mmstick** [comment]
A pull request for Rust or for this crate?

**Comment by alexcrichton** [comment]
ah presumably for this crate, I suspect the bug is not with the standard library

**Comment by mmstick** [comment]
I see that an "." Path is interpreted as `Component::CurDir` which matches to `continue` without setting `emitted` to true which triggers the error.

**Comment by mmstick** [comment]
After changing `continue` to `{}`, I am now able to create the hidden directory.

**Comment by alexcrichton** [comment]
Ah yeah that was meant to encode paths like `foo/./bar` as `foo/bar`, but if there's only one `CurDir` that should perhaps be treated specially

**Comment by mmstick** [comment]
Added a check to see if there is only one instance of CurDir with

```rust
let cur_dir_is_path = path.components().filter(|x| x == &Component::CurDir).count() == 1;
```

And then added a separate match test

```rust
Component::CurDir if cur_dir_is_path => {},
```

This continues to work without causing an error.

**Comment by opilar** [comment]
I make a little test and it passed:
```rust
let td = t!(TempDir::new("tar-rs"));
let mut ar = Builder::new(Vec::new());
let tmppath = td.path().join("tmpfile");
t!(t!(File::create(&tmppath)).write_all(b"c"));
t!(ar.append_dir(".", "."));
t!(ar.append_file("./a", &mut t!(File::open(&tmppath))));
t!(ar.finish());
```

**Comment by mmstick** [comment]
This was implemented a while ago, so I'll close this.
