### ISSUE TITLE
Unable to parse Cargo.toml in rust 1.5

### ISSUE THREAD

**Issue by Qard** [alexcrichton/tar-rs#83]
There seems to be issues parsing [line 27 of Cargo.toml](https://github.com/alexcrichton/tar-rs/blob/master/Cargo.toml#L27) in rust 1.5. I upgraded to 1.10 and it works fine there, so not sure how much that matters. Just figured I should let you know. 😺

**Comment by alexcrichton** [comment]
Thanks for the report! But yeah for now this crate requires a Cargo with support for that kind of syntax for dependencies, so it's not intended to work with 1.5.
