### ISSUE TITLE
Fix for symlink attack needs to support extracting symlinks pointing outside the root

### ISSUE THREAD

**Issue by joshtriplett** [alexcrichton/tar-rs#87]
Thanks for fixing the symlink attack.  However, the fix in 85b6399b212f66eb955431f214e0e9eb408988c8, while addressing the vulnerability, also prevents extracting valid archives that contain a symlink pointing outside the root, even if nothing attempts to write "through" those symlinks.  As an example of such a valid tarball, consider extracting the filesystem tarball from a Debian package into a temporary directory.  Such a tarball could legitimately contain, for instance, a symlink like `/usr/bin/vi -> /etc/alternatives/vi`; that shouldn't cause extracting the archive to a temporary directory to fail.  It's even OK to have a symlink to a directory outside the root, as long as nothing gets extracted *through* that symlink.

The fix for busybox (in https://bugs.busybox.net/show_bug.cgi?id=8411) used the approach of writing a "placeholder" for such symlinks, and replacing all of the placeholders with symlinks at the end of the extraction; then, if anything attempts to extract "through" that placeholder, it'll fail.

**Comment by alexcrichton** [comment]
Yeah that seems like a more reasonable fix to me. This'd unfortunately be a bit more difficult to implement, but not impossible! I'd be down for a PR
