### ISSUE TITLE
Add support for checking stats for tar::File

### ISSUE THREAD

**Issue by ghost** [alexcrichton/tar-rs#9]
Add `stat()` and `lstat()` methods for returning `std::io::FileStat` values for flexible checking in `tar::File`s.

**Comment by alexcrichton** [comment]
I've just pushed a somewhat significant revamp of the API, and all information like this is currently exposed through `Header`. There's no way to return a raw `fs::Metadata` now as there's no constructor, and the files don't really have the precise equivalent of this to justify returning it right now. As a result I'm going to close this as I believe it's sufficiently covered by `Header`
