### ISSUE TITLE
appending symbolic links to builder

### ISSUE THREAD

**Issue by clux** [alexcrichton/tar-rs#95]
Hi,

I'm trying to basically tar up a directory as is by walking a tree and adding the files therein, but am noticing that the symlinks that exists in the folder are duplicated as an actual full dereferenced copy in the archive. Is there a sane way to add symlinked files? Been grepping the tests and docs, but not really gotten any wiser.

This is what I've got:

```rust
    // pipe builder -> encoder -> file
    let file = File::create(&tarball)?;
    let mut encoder = GzEncoder::new(file, Compression::Default); // encoder writes file
    let mut builder = tar::Builder::new(&mut encoder); // tar builder writes to encoder

    let files = WalkDir::new("OUTPUT")
        .min_depth(1)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| !e.path().is_dir()); // ignore directories (these are created anyway)

    for f in files {
        let pth = f.path().strip_prefix("OUTPUT").unwrap();
        debug!("-> {}", pth.display());
        let mut f = File::open(f.path())?;
        builder.append_file(pth, &mut f)?;
    }
```

which causes symlinks to be copied.

From the looks of it one can do something with an explicit `Header` and `set_link_names` and using `builder.append()`, when something is a symlink. So have tried  doing a match on `fs::symlink_metadata(pth)`, and use `builder.append()` when it was a link using:

```rust
                    let mut h = Header::new_gnu();
                    h.set_path(pth).unwrap();
                    h.set_size(0);
                    let data : &[u8] = &[];
                    let f = fs::read_link(pth)?;
                    h.set_link_name(f)?;
                    builder.append(&h, data)?;
```

and the builder lets me do this, but this creates a damaged archive that `tar tvf` complains about. Any help / documentation on adding links would be great. I just want to do the equivalent of `tar czvf mytar.tar OUTPUT`

**Comment by alexcrichton** [comment]
Yeah right now the "easiest" way to do this is as you've found by creating a header manually and then appending it.

We could consider adding a new `append_foo` function though which doesn't traverse symlinks.

**Comment by ids1024** [comment]
@alexcrichton Would it be acceptable to add this as state to the builder, with something like `builder.follow_symlinks(false)`?

**Comment by alexcrichton** [comment]
Certainly!
