### ISSUE TITLE
Expose Gnu LongName header extension

### ISSUE THREAD

**Issue by stuhood** [alexcrichton/tar-rs#97]
`Builder::append_file` and `Builder::append_file` implement support for `LongName` via `builder::append_fs`, which writes two Headers if necessary to store the filename. But (understandably) `Builder::append` does not.

Users who need to strip or manipulate the file metadata while taring something (in particular, because they're looking for reproducible, byte-identical output) might use the `Builder::append` method with a `Header` containing only normalized metadata; but unfortunately, this will not trigger the `LongName` extension, meaning that that feature would need to be implemented by the caller.

----

I don't really see a really obvious way to expose the `LongName` logic with the current API, since the caller will fail in `Header::set_path`, and the extension requires not just another Header but also some content in the entry.

One option might be to add a synthetic Header type (ie, one that is not exactly 512 bytes in length) that will accept all data that can possibly be appended when extensions are in play: ie, has an unbounded `path` length. Then, during `append` for this Header type, usage of extensions would be pre-acknowledged.

**Comment by stuhood** [comment]
Happy to implement this if there is a reasonable approach!

**Comment by alexcrichton** [comment]
Thanks for the issue! I wonder if we could perhaps tackle this through two separate avenues:

1. Add a `deterministic` flag to `Builder`. When set it could ensure that deterministic archives were ignoring, ignoring metadata such as mtime/atime/etc.
2. Add a new method, `append_name` (or something like that) which takes a `&Path`, a `&mut Header`, and a `&mut Read`. That'd auto add a LongName header ahead of time if necessary and otherwise just put the `Path` into the `Header` provided. 

How's that sound?

**Comment by stuhood** [comment]
Thanks @alexcrichton ! Either of those would be reasonable. `(1)` sounds like the most general option... `(2)` is a tiny fraction better for my usecase (we can use information from previous syscalls to populate the size, so `append_fs`'s lookup of the metadata is extraneous).

Calling my "synthetic header type" suggestion option `(3)`, I'd wonder whether there are any other extensions that might benefit from looser constraints at header construction time... if so, then continuing to overload the `append*` methods (ie, `(2)`) could get hairy.

**Comment by alexcrichton** [comment]
Yeah it's true that there's turning out to be quite a few append functions... 

We could at least update [`set_metadata`](https://docs.rs/tar/0.4.10/tar/struct.Header.html#method.set_metadata) to have a `set_metadata_deterministic` or something like that. I'm ok having more than a few options though for ergonomics! (whatever makes the most sense)

**Comment by stuhood** [comment]
Will tackle this this weekend. Leaning toward option (1), but let me know if you'd rather something else.

**Comment by alexcrichton** [comment]
👍

**Comment by stuhood** [comment]
Fixed in #99
